require:
  - rubocop-packaging

AllCops:
  TargetRubyVersion: 3.1 # keep in sync with minimum version
  Exclude:
  - vendor/**/*
  - gemfiles/vendor/**/*
  - lib/fast_gettext/vendor/**/*
  - spec/**/* # TODO
  - gemfiles/**/* # TODO

Metrics:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false

Style/WordArray:
  EnforcedStyle: brackets

Style/IfUnlessModifier:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Naming/MethodName:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/PerlBackrefs:
  Enabled: false

Style/DoubleNegation:
  Enabled: false
