name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '3.1', '3.2', '3.3', '3.4' ]
        task: [ 'default' ]
        gemfile: [ 'rails71' ]
        include:
        - ruby: '3.1' # lowest supported version
          task: rubocop
          gemfile: rails71
    name: ${{ matrix.ruby }} ${{ matrix.gemfile }} rake ${{ matrix.task }}
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
      RUBYOPT: "--enable-frozen-string-literal"
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rake
  benchmark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1' # lowest supported version
        bundler-cache: true
    - run: gem i gettext && gem i activesupport && bundle exec rake benchmark
  namespaces:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1' # lowest supported version
        bundler-cache: true
    - run: echo 'gem "gettext"' >> Gemfile && echo 'gem "iconv"' >> Gemfile && bundle config unset deployment && bundle && bundle exec rake namespaces
